pool:
  vmImage: 'macOS-latest'
steps:

- script: xcodebuild -version
  displayName: Xcode version

- script: xcodebuild -workspace $(Build.SourcesDirectory)/Loop.xcworkspace -list
  displayName: Schemes in workspace

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/Loop.xcworkspace'
    scheme: 'Loop (Workspace)'
    packageApp: true
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)' 
    artifactName: 'drop' 
    publishLocation: 'Container'