pool:
  vmImage: 'macOS-latest'
steps:

#- script: xcodebuild -version
#  displayName: Xcode version

#- script: xcodebuild -workspace $(Build.SourcesDirectory)/Loop.xcworkspace -list
#  displayName: Schemes in workspace

#- script: xcodebuild -showsdks
#  displayName: Xcode SDKs

- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: '$(p12FileName)'
   certPwd: '$(p12Password)'
   keychain: 'temp'
   deleteCert: true  

- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(provisioningProfile)'
   removeProfile: true

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Debug'
    sdk: 'iphoneos'
    useXcpretty: false
    xcWorkspacePath: '**/Loop.xcworkspace'
    scheme: 'Loop (Workspace)'
    packageApp: true
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)' 
    artifactName: 'drop' 
    publishLocation: 'Container'

    